# Generated by Django 4.2.5 on 2024-01-12 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shophummin', '0002_remove_orderitem_product_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Products_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_image2', models.ImageField(blank=True, upload_to='images/product/%Y/%m/%d')),
                ('products_image3', models.ImageField(blank=True, upload_to='images/product/%Y/%m/%d')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shophummin.product')),
            ],
        ),
    ]
