# Generated by Django 4.2.5 on 2024-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophummin', '0003_product_brand_product_comments_product_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='authority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
