# Generated by Django 4.2.5 on 2024-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophummin', '0004_invoice_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/product/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/product/%Y/%m/%d'),
        ),
    ]
