# Generated by Django 4.2.5 on 2024-02-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophummin', '0005_product_image2_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cpost',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='family',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phon',
            field=models.TextField(blank=True),
        ),
    ]
